"""Common legacy block ids, for readable code (``blocks.GOLD_BLOCK`` beats ``41``).

These are the classic numeric ids the mcpi protocol uses. A handful of blocks take a
``data`` value (e.g. wool colour); pass it as the ``data`` argument to ``set_block``.
"""

AIR = 0
STONE = 1
GRASS = 2
DIRT = 3
COBBLESTONE = 4
WOOD_PLANKS = 5
SAPLING = 6
BEDROCK = 7
WATER = 8
WATER_STATIONARY = 9
LAVA = 10
LAVA_STATIONARY = 11
SAND = 12
GRAVEL = 13
GOLD_ORE = 14
IRON_ORE = 15
COAL_ORE = 16
WOOD = 17
LEAVES = 18
GLASS = 20
LAPIS_LAZULI_ORE = 21
LAPIS_LAZULI_BLOCK = 22
SANDSTONE = 24
BED = 26
COBWEB = 30
GRASS_TALL = 31
WOOL = 35  # data = colour (0 white, 14 red, 11 blue, 4 yellow, 5 green, ...)
FLOWER_YELLOW = 37
FLOWER_CYAN = 38
MUSHROOM_BROWN = 39
MUSHROOM_RED = 40
GOLD_BLOCK = 41
IRON_BLOCK = 42
STONE_SLAB_DOUBLE = 43
STONE_SLAB = 44
BRICK_BLOCK = 45
TNT = 46
BOOKSHELF = 47
MOSS_STONE = 48
OBSIDIAN = 49
TORCH = 50
FIRE = 51
STAIRS_WOOD = 53
CHEST = 54
DIAMOND_ORE = 56
DIAMOND_BLOCK = 57
CRAFTING_TABLE = 58
FARMLAND = 60
FURNACE_INACTIVE = 61
FURNACE_ACTIVE = 62
DOOR_WOOD = 64
LADDER = 65
STAIRS_COBBLESTONE = 67
GLOWSTONE_BLOCK = 89
BEDROCK_INVISIBLE = 95
STAINED_GLASS = 95
ICE = 79
SNOW_BLOCK = 80
CACTUS = 81
CLAY = 82
SUGAR_CANE = 83
FENCE = 85
GLOWING_OBSIDIAN = 246

# a few handy wool/colour data values
WOOL_WHITE = 0
WOOL_ORANGE = 1
WOOL_MAGENTA = 2
WOOL_YELLOW = 4
WOOL_LIME = 5
WOOL_PINK = 6
WOOL_LIGHT_BLUE = 3
WOOL_BLUE = 11
WOOL_GREEN = 13
WOOL_RED = 14
WOOL_BLACK = 15
